moviesapp/urls.py
from django.urls import path,include
from . import views
app_name='moviesapp'
urlpatterns = [
       path('',views.index,name='index'),
       path('movie/<int:movie_id>/',views.detail,name='detail'),
       path('add/',views.add,name='add'),
       path('update/<int:id>/',views.update,name='update')



]

moviesproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('moviesapp.urls'))
]
if settings.DEBUG:
      urlpatterns += static(settings.STATIC_URL,
				    document_root=settings.STATIC_ROOT)
      urlpatterns += static(settings.MEDIA_URL,
		 			document_root=settings.MEDIA_ROOT)

moviesapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
        name=models.CharField(max_length=250)
        year=models.IntegerField()
        descr=models.TextField()
        img=models.ImageField(upload_to='movie_pics')

        def __str__(self):
         return self.name

moviesapp/forms.py
from django import forms
from .models import movies


class MovieForm(forms.ModelForm):
         class Meta:
            model=movies
            fields=['name','year','descr','img']

moviesapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movies
from . forms import MovieForm
# Create your views here.
def index(request):

      movie=movies.objects.all()
      context={

            'movie_list':movie
      }

      return render(request,"index.html",context)

def detail(request,movie_id):
      movie=movies.objects.get(id=movie_id)

      return render(request,"detail.html",{'movie':movie})
def add(request):
      if request.method=='POST':
            name=request.POST.get('name',)
            descr = request.POST.get('descr',)
            year = request.POST.get('year',)
            img = request.FILES['img']
            movie=movies(name=name,descr=descr,year=year,img=img)
            movie.save();
      return render(request,"add.html")

def update(request,id):
      movie=movies.objects.get(id=id)

      form=MovieForm(request.POST or None, request.FILES,instance=movie)
      if form.is_valid():
            form.save()
            return redirect('/')
      return render(request,"update.html",{'movie':movie,'form':form})

templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post" ENCTYPE="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your movie name"><br>
        <input type="text" name="descr" placeholder="enter your movie description"><br>
        <input type="text" name="year" placeholder="enter your movie year"><br>
        <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}


</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      MalluRockers
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<h1 align="center"><u>{{movie.name}}</u></h1><br>
<p align="center">{{movie.year}}</p><br>
<center><img src="{{movie.img.url}}" height="300" width="300"></center>
{{movie.descr}}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-3">
            <div class="card" style="width: 16rem;height:330px;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5><hr>
                    <p class="card-text"></p>
                    <a href="{% url 'moviesapp:detail' i.id %}" class="btn btn-primary">view</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/update.html
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{from.as_p}}


</form>